spring.application.name=Hospital_Management_System



spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
server.port=${PORT:8080}


jwt.secret= "hvcieviyvayckyvkvskeyuscyHBeyvgcbmhsnregfbyegei"
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

